version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules  # Fixed to avoid mapping issues
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules  # Fixed to avoid mapping issues
    ports:
      - '5000:5000'
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - MONGODB_URI  # Use the MONGODB_URI from the .env file

networks:
  default:
    external:
      name: web
